chore: add linting in CI

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -39,6 +39,22 @@ jobs:
             exit 1
           fi
 
+  lint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: cachix/install-nix-action@v31
+        with:
+          nix_path: nixpkgs=channel:nixos-unstable
+      - name: Check Nix formatting
+        run: |
+          echo "Checking Nix lints..."
+          nix-shell -p statix --run "statix check"
+          if [ $? -ne 0 ]; then
+            echo "Error: Some Nix files have linting issues."
+            exit 1
+          fi
+
   find-systems:
     runs-on: ubuntu-latest
     outputs:
