fix: standalone installation script

diff --git a/.github/workflows/continuous-integration.yml b/.github/workflows/continuous-integration.yml
--- a/.github/workflows/continuous-integration.yml
+++ b/.github/workflows/continuous-integration.yml
@@ -14,6 +14,12 @@ jobs:
           nix_path: nixpkgs=channel:nixos-25.05
       - name: Run configuration script
         run: ./scripts/debian/configure-dotfiles.sh
+      - name: Verify home-manager is installed
+        run: |
+          if ! command -v home-manager &> /dev/null; then
+            echo "home-manager could not be found"
+            exit 1
+          fi
 
   nix-fmt:
     runs-on: ubuntu-latest
